RODA_SERVICES = {
    'security@facebookmail.com': 'Facebook',
    'security@mail.instagram.com': 'Instagram',
    'register@account.tiktok.com': 'TikTok',
    'info@x.com': 'Twitter',
    'security-noreply@linkedin.com': 'LinkedIn',
    'no-reply@accounts.snapchat.com': 'Snapchat',
    'noreply@discord.com': 'Discord',
    'email@discord.com': 'Discord',
    'noreply@telegram.org': 'Telegram',
    'no-reply@whatsapp.com': 'WhatsApp',
    'noreply@steampowered.com': 'Steam',
    'xboxreps@engage.xbox.com': 'Xbox',
    'noreply@xbox.com': 'Xbox',
    'reply@txn-email.playstation.com': 'PlayStation',
    'help@acct.epicgames.com': 'EpicGames',
    'no-reply@epicgames.com': 'Epic',
    'noreply@rockstargames.com': 'Rockstar',
    'EA@e.ea.com': 'EA Sports',
    'noreply@ubisoft.com': 'Ubisoft',
    'noreply@blizzard.com': 'Blizzard',
    'no-reply@riotgames.com': 'Riot Games',
    'noreply@valorant.com': 'Valorant',
    'noreply@hoyoverse.com': 'Genshin Impact',
    'noreply@pubgmobile.com': 'PUBG',
    'accounts@roblox.com': 'Roblox',
    'noreply@mojang.com': 'Minecraft',
    'noreply@id.supercell.com': 'Supercell',
    'no-reply@accounts.nintendo.com': 'Nintendo',
    'noreply@valvesoftware.com': 'Valve/CSGO/Dota2',
    'noreply@activision.com': 'Activision',
    'noreply@bethesda.net': 'Bethesda',
    'noreply@2k.com': '2K Games',
    'no-reply@warframe.com': 'Warframe',
    'info@account.netflix.com': 'Netflix',
    'no-reply@spotify.com': 'Spotify',
    'no-reply@twitch.tv': 'Twitch',
    'no-reply@youtube.com': 'YouTube',
    'no-reply@disneyplus.com': 'Disney+',
    'account@hulu.com': 'Hulu',
    'no-reply@hbomax.com': 'HBO Max',
    'auto-confirm@amazon.com': 'Amazon Prime',
    'no-reply@apple.com': 'Apple TV+',
    'noreply@crunchyroll.com': 'Crunchyroll',
    'info@Exxen.com': 'Exxen',
    'info@Tod.com': 'Tod',
    'info@Tabii.com': 'Tabii',
    'noreply@blutv.com': 'BluTV',
    'account-update@amazon.com': 'Amazon',
    'newuser@nuwelcome.ebay.com': 'eBay',
    'no-reply@shopify.com': 'Shopify',
    'transaction@etsy.com': 'Etsy',
    'no-reply@aliexpress.com': 'AliExpress',
    'no-reply@walmart.com': 'Walmart',
    'noreply@trendyol.com': 'Trendyol',
    'info@pazarama.com': 'Pazarama',
    'noreply@hepsiburada.com': 'Hepsiburada',
    'noreply@n11.com': 'N11',
    'noreply@gg.com': 'GittiGidiyor',
    'noreply@ciceksepeti.com': '
